name: tolki_chat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_smart_dialog: ^4.9.8+1
  connectivity_plus: ^6.0.5
  flutter_svg: ^2.0.10+1
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/